EasyEngine/site-type-wp

- .travis.yml
- ci/prepare.sh
- features/bootstrap/FeatureContext.php
- features/labels.feature
- features/redirect.feature
- features/site.feature
- src/Site_WP_Command.php
Depends on: https://github.com/EasyEngine/easyengine/pull/1140
> Update for EE::launch changes in core

- src/Site_WP_Command.php
> Fix php reload command

- src/Site_WP_Command.php
- src/Site_WP_Docker.php
- templates/config/php-fpm/php.ini.mustache
> Remove mailhog service as default

- src/Site_WP_Command.php
Depends on https://github.com/EasyEngine/easyengine/pull/1155
> Update db for wildcard

- features/bootstrap/FeatureContext.php
> Fix labels test

- src/Site_WP_Command.php
- src/Site_WP_Docker.php
Depends on: https://github.com/EasyEngine/easyengine/pull/1163
> Update for mailhog command

- ci/prepare.sh
- src/Site_WP_Docker.php
Depends on: https://github.com/EasyEngine/easyengine/pull/1166
Changes in accordance to issue: https://github.com/EasyEngine/easyengine/issues/1156
> Get image versions from utils

- composer.json
- features/bootstrap/FeatureContext.php
- features/redirect.feature
- features/site.feature
- src/Site_WP_Command.php
Corrects flag.(Use --ssl instead of --le)
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Correct ssl behaviour

- src/Site_WP_Command.php
Issue ref - https://github.com/EasyEngine/site-wp-command/issues/18
closes https://github.com/EasyEngine/site-wp-command/issues/18
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Add per site db user

- src/Site_WP_Command.php
Also corrects WordPress spelling
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Remove --wp option

- src/Site_WP_Command.php
This PR solves inconsistencies of hyphens and underscore
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Change underscores to hyphen

- ci/prepare.sh
- src/WordPress.php
> Refactor db code

- src/WordPress.php
Fixes https://github.com/EasyEngine/site-wp-command/issues/33
> Update url with proper prefix

- src/WordPress.php
> Fix getting mail parameter

- src/WordPress.php
issue: https://github.com/EasyEngine/site-command/issues/110
> Remove reload_proxy_configuration

- features/site.feature
- src/Site_WP_Docker.php
- templates/config/nginx/default.conf.mustache
- templates/docker-compose.mustache
This PR fixes creation of redis site and also adds tests for redis site creation.
> Fix redis site creation

- features/bootstrap/FeatureContext.php
> Add leftout sites in cleanup list

- src/Site_WP_Docker.php
- src/WordPress.php
Depends on https://github.com/EasyEngine/site-command/pull/128
> Update to accomodate global db

- src/Site_WP_Docker.php
- src/WordPress.php
Fixes https://github.com/EasyEngine/site-command/issues/126
> Fix https issue with proper docker-compose gen

- src/WordPress.php
Depends on https://github.com/EasyEngine/cron-command/pull/20
Closes #35
> Fix wp cron errors

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
Closes: https://github.com/EasyEngine/site-type-wp/issues/59
Depends on https://github.com/EasyEngine/service-command/pull/5
Tests will be failing till it is merged.
> Add global-redis and update service call of global services

- .travis.yml
- features/bootstrap/FeatureContext.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1233
> Change unix path in site-type-wp

- features/bootstrap/FeatureContext.php
closes: https://github.com/EasyEngine/site-command/issues/144
Depends on: https://github.com/EasyEngine/site-command/pull/143
> Fix site path in site-type-wp

- features/bootstrap/FeatureContext.php
closes: https://github.com/EasyEngine/site-command/issues/144
Dipends on:https://github.com/EasyEngine/site-command/pull/145
Fix site path issue.
> Fix site root path issue

- features/bootstrap/FeatureContext.php
- features/redirect.feature
- src/WordPress.php
Depends on: https://github.com/EasyEngine/site-command/pull/139
> fix curl error on subdomain in site-type-wp

- src/WordPress.php
closes: https://github.com/EasyEngine/site-type-wp/issues/67
> Handle certificate inherit problem check

- src/WordPress.php
issue ref: https://github.com/EasyEngine/site-command/issues/146
Depends on: https://github.com/EasyEngine/site-command/pull/156
> Add database entry for cache_host(wp)

- src/WordPress.php
> Update cron execution and time interval

- src/WordPress.php
> Update default db charset to utf8mb4

- src/WordPress.php
Closes https://github.com/EasyEngine/site-type-wp/issues/42
> Fix remote db working

- src/WordPress.php
Depends on https://github.com/EasyEngine/site-command/pull/158
Issue ref https://github.com/EasyEngine/site-command/issues/157
> Add try-catch handling if db user creation fails

- src/WordPress.php
> Add nginx-helper plugin data to options table

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
closes: https://github.com/EasyEngine/easyengine/issues/1237
Similar PR for PHP package: https://github.com/EasyEngine/site-type-php/pull/24
> Fix page cache persistent bug

- src/WordPress.php
closes: https://github.com/EasyEngine/site-type-wp/issues/80
> Change default WordPress username 

- src/WordPress.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1244
Depends on: https://github.com/EasyEngine/site-command/pull/174
> Add check for max sites

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
- templates/docker-compose.mustache
Issue ref https://github.com/EasyEngine/site-command/issues/187
Depends on EasyEngine/dockerfiles#40
Depends on https://github.com/EasyEngine/site-command/pull/188
> Update docker volume mounting

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
Issue ref EasyEngine/dockerfiles#42
Depends on EasyEngine/site-command#190
Depends on EasyEngine/dockerfiles#43
> Fix configurations

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
Issue ref: EasyEngine/dockerfiles#42
Depends on: EasyEngine/dockerfiles#46
Signed-off-by: Riddhesh Sanghvi riddheshsanghvi96@gmail.com
> Update nginx configuration directories

- src/Site_WP_Docker.php
- src/WordPress.php
> Add php logs

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/nginx/main.conf.mustache
Issue ref: EasyEngine/dockerfiles#51
Depends on EasyEngine/easyengine#1256
Depends on EasyEngine/easyengine#1269
> Consolidate configuration

- src/Site_WP_Docker.php
Issue ref: https://github.com/EasyEngine/site-command/issues/205
> Fix nohttps in docker-compose generation

- src/WordPress.php
> Remove beta warning

- src/WordPress.php
Changes related to: https://github.com/EasyEngine/dockerfiles/pull/60
Depends on: https://github.com/EasyEngine/site-command/pull/215
> Update php.ini path

- src/WordPress.php
Closes: https://github.com/EasyEngine/cron-command/issues/40
> Randomise cron to prevent multiple cron execution at same time

- src/WordPress.php
> Add site root in info

- src/Site_WP_Docker.php
- templates/docker-compose.mustache
Issue ref: https://github.com/EasyEngine/site-command/issues/218
> Fix loopback request to site

- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/php-fpm/php.ini.mustache
Closes: https://github.com/EasyEngine/site-command/issues/223
Depends on: https://github.com/EasyEngine/easyengine/pull/1303
Depends on: https://github.com/EasyEngine/site-command/pull/224
> Add support for PHP 5.6

- src/Site_WP_Docker.php
- src/WordPress.php
> Fix 5.6 checks

- src/WordPress.php
> Add --vip flag and setup VIP Go environment.

- src/WordPress.php
closes https://github.com/EasyEngine/easyengine/issues/1315
> Fix site reload issue

- src/WordPress.php
> Update username to randomly generated user

- ci/prepare.sh
Closes: https://github.com/EasyEngine/easyengine/issues/1262
> Remove nightly tag from images

- src/Site_WP_Docker.php
> Fix cache network bridging for rds scenario

- src/Site_WP_Docker.php
- src/WordPress.php
Closes: https://github.com/EasyEngine/easyengine/issues/1331
> Fix network issue with local containers

- src/WordPress.php
Depends on: https://github.com/EasyEngine/site-command/pull/260
Issue ref: https://github.com/EasyEngine/feature-requests/issues/64
> Add WordPress configurations for site publish.

- src/WordPress.php
Examples for changes in: https://github.com/EasyEngine/site-command/pull/258
> Add example for self-signed cert

- src/Site_WP_Docker.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1346
Depends on: https://github.com/EasyEngine/site-command/pull/265
> Update setting ssl-policy env variable

- src/WordPress.php
issue: https://github.com/EasyEngine/site-command/issues/271
> Add host entry for site create with self SSL

- src/WordPress.php
Depends on: https://github.com/EasyEngine/site-command/pull/267
closes: https://github.com/EasyEngine/site-command/issues/257
> Add parent site ssl certificate check before site creation

- src/WordPress.php
> Fix multisite login issue

- src/WordPress.php
> Fix Array to string conversion in site publish

- migrations/container/20181224104940_site-type-wp_set_mu_cookie_domain.php
Migrations for changes related to: https://github.com/EasyEngine/site-type-wp/pull/127
Issue ref: https://github.com/EasyEngine/site-type-wp/issues/126
> Add migrations for mu login issue

- src/WordPress.php
Issue ref: https://github.com/EasyEngine/site-command/issues/276
Depends on: https://github.com/EasyEngine/site-command/pull/275
> Rename publish to share

- src/WordPress.php
> Set and remove post configurations of WP_HOME and WP_SITEURL for site share

- src/WordPress.php
> Fix site-name detection in restart

- src/WordPress.php
closes: https://github.com/EasyEngine/site-command/issues/292
Depends on: 
https://github.com/EasyEngine/site-command/pull/295
https://github.com/EasyEngine/site-type-php/pull/63/files
> Add custom ssl support for wp site

- migrations/container/20190213105615_site-type-wp_update_env_file_with_newrelic_key.php
- src/Site_WP_Docker.php
- src/WordPress.php
- templates/config/.env.mustache
Issue ref: EasyEngine/easyengine#1390
Depends on: EasyEngine/easyengine#1392
Depends on: https://github.com/EasyEngine/service-command/pull/56
> Add env and docker-compose configuration for newrelic

- src/Site_WP_Docker.php
- src/WordPress.php
Depends on: https://github.com/EasyEngine/easyengine/pull/1407
> Add support for PHP 7.3

- src/WordPress.php
> Add support for php 7.0

- src/WordPress.php
- templates/config/php-fpm/php.ini-56.mustache
> Add ssmtp config for PHP 5.6

- src/WordPress.php
> Make PHP 7.4 default PHP version

- src/WordPress.php
> Add check for strong password in input

- src/WordPress.php
Depends on https://github.com/EasyEngine/site-command/pull/326
> Add feature for creating site with proxy-cache

- src/Site_WP_Docker.php
- src/WordPress.php
Depends on https://github.com/EasyEngine/site-command/pull/329
> Add alias domain feature in site create

- src/WordPress.php
> Restrict alias domains to subdom MU sites

- src/WordPress.php
Depends on https://github.com/EasyEngine/site-command/pull/337
> Check alias domains while site creation

- src/WordPress.php
> Add proxy cache status in site info

- src/WordPress.php
> Add alias domain example in site create

- src/WordPress.php
Reverts EasyEngine/site-type-wp#163
> Revert "Restrict alias domains to subdom MU sites"

- src/WordPress.php
Ref: https://github.com/EasyEngine/site-command/pull/341
> Remove filter_var check due to wildcard domains

- src/WordPress.php
> Increase health check tries for slow local machines

- src/WordPress.php
- templates/config/nginx/admin-tools.conf.mustache
- templates/config/nginx/main.conf.mustache
Ref: EasyEngine/admin-tools-command#45
Signed-off-by: dhsathiya <devarshisathiya5@gmail.com>
> Add config for ee-admin

- templates/config/nginx/main.conf.mustache
Ref: https://github.com/EasyEngine/site-command/issues/364
> Disable js css nginx log

- src/WordPress.php
Closes: https://github.com/EasyEngine/feature-requests/issues/93
Depends on https://github.com/EasyEngine/easyengine/pull/1647
> Add support for WP_ENVIRONMENT_TYPE

- src/WordPress.php
Ref:- https://docs.wpvip.com/how-tos/local-development/#h-step-4-update-wp-config-php
> Add support to load early dependencies if vip flag is defined

- src/WordPress.php
Closes: https://github.com/EasyEngine/easyengine/issues/1690
> Enable mailhog by default if dev/local

- src/WordPress.php
Extension for https://github.com/EasyEngine/site-type-wp/pull/212
> Add staging env for mailhog

- src/WordPress.php
Depends on https://github.com/EasyEngine/easyengine/pull/1700
> Update with global compose-exec helper function
